apiVersion: v1
data:
  mesh: |-
    accessLogFile: /dev/stdout
    extensionProviders:
    - name: asm-oauth
      envoyExtAuthzHttp:
        service: oauth-proxy.asm-oauth.svc.cluster.local
        port: 4180
        includeHeadersInCheck: ["authorization", "cookie"]
        headersToUpstreamOnAllow: ["x-forwarded-access-token", "authorization", "path", "x-auth-request-user", "x-auth-request-email", "x-auth-request-access-token"]
        headersToDownstreamOnDeny: ["content-type", "set-cookie"]
        includeAdditionalHeadersInCheck:
            X-Auth-Request-Redirect: 'https://%REQ(:authority)%%REQ(:path)%'
kind: ConfigMap
metadata:
  name: istio-asm-managed-rapid
  namespace: istio-system
