apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - configmap.yaml
  - serviceaccount.yaml
  - role.yaml
  - deployment.yaml
  - service.yaml
  - autoscaling-v2.yaml
  - gateway.yaml

namespace: asm-oauth

# Patch the Istio ingress service so that our IP is used.
patches:
- patch: |-
    - op: add
      path: /spec/loadBalancerIP
      value: 34.47.11.52
  target:
    kind: Service
    name: istio-ingressgateway
    version: v1

# patch the overriden namespace value
# See https://github.com/kubernetes-sigs/kustomize/issues/880#issuecomment-1736323724
transformers:
- |-
  apiVersion: builtin
  kind: PatchTransformer
  metadata:
    name: istio-asm-managed-rapid
  patch: '[{"op": "replace", "path": "/metadata/namespace", "value": "istio-system"}]'
  target:
    group: ""
    kind: ConfigMap
