apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - serviceaccount.yaml
  - role.yaml
  - deployment.yaml
  - service.yaml
  - autoscaling-v2.yaml
  - gateway.yaml

namespace: asm-oauth
